### PR TITLE
[2.0] Improve URIHelper::parse_url

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement

### Introduction

The `URIHelper::parse_url()` is used in all `JRoute::_()` calls in the cms (ex: building menus, breadcrumbs, sef, etc) so is a very used method.
Also one as to take in consideration that most cms URLs passing trough cms `JRoute::_()` are not utf-8 (ex: `index.php?Itemid=222`)
Improving it's performance will do is little part in improving performance in the CMS.

So this PR tries to improve it's performance by only using the custom parse_url function when the url has utf-8 chars.

### Summary of Changes

Improves performance of URIHelper::parse_url.
Also adds the component parameter as native parse_url.

### Testing Instructions

- Unit tests pass
- Code review
- To test use the following code in a cms 4.0 template index.php before and after the PR
```php
use \Joomla\Uri\UriHelper;

$iterationsPerUrl = 1000;
$uriToTest = [
	'index.php',
	'index.php?ItemId=122',
	'/index.php/username-reminder?view=remind',
	'https://domain.tld/',
	'https://domain.tld/en/about?a=b#anchor',
	'https://domain.tld/path/script.php?foo=%21%2A%27%28%29%3B%3A%40%26%3D%24%2C%2F%3F%23%5B%5D&bar=foo#anchor',
	'https://do身ain.tld/中文/纹身馆简介你好/媒体报道',
];


foreach ($uriToTest as $url)
{
	$start = microtime(true);
	for ($i = 1; $i <= $iterationsPerUrl; $i++)
	{
		UriHelper::parse_url($url);
	}
	echo '- [' . number_format(((microtime(true) - $start) * 1000), 3) . ' ms] Processing ' . $url . '' .PHP_EOL;
}
```

My best results on PHP 7.0.19 in Linux for this urls parsed:
- Before:
```
- [2.133 ms] Processing index.php
- [3.315 ms] Processing index.php?ItemId=122
- [3.894 ms] Processing /index.php/username-reminder?view=remind
- [4.136 ms] Processing https://domain.tld/
- [6.849 ms] Processing https://domain.tld/en/about?a=b#anchor
- [10.411 ms] Processing https://domain.tld/path/script.php?foo=%21%2A%27%28%29%3B%3A%40%26%3D%24%2C%2F%3F%23%5B%5D&bar=foo#anchor
- [11.326 ms] Processing https://do身ain.tld/中文/纹身馆简介你好/媒体报道
```
- After:
```
- [0.566 ms] Processing index.php
- [0.826 ms] Processing index.php?ItemId=122
- [0.943 ms] Processing /index.php/username-reminder?view=remind
- [0.984 ms] Processing https://domain.tld/
- [1.322 ms] Processing https://domain.tld/en/about?a=b#anchor
- [1.850 ms] Processing https://domain.tld/path/script.php?foo=%21%2A%27%28%29%3B%3A%40%26%3D%24%2C%2F%3F%23%5B%5D&bar=foo#anchor
- [4.407 ms] Processing https://do身ain.tld/中文/纹身馆简介你好/媒体报道
```
### Documentation Changes Required

None.

@frankmayer can you also review this.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
does anyone as Mac and/or Windows to test if all works in those systems?

In Linux this seems to work fine and tests work fine too.

**Comment by frankmayer** [comment]
@andrepereiradasilva will do (within a few days).

**Comment by andrepereiradasilva** [comment]
removed all setlocale stuff, now just check is string has utf8 chars

**Comment by frankmayer** [comment]
Looks fine on code review.
Sorry, I haven't gotten to setup a Joomla 4 Test environment yet. I can look into that after a few days, if there is still need for that.
BTW, nice improvement. will surely do its part in overall performance of Joomla.
Thanks

**Comment by andrepereiradasilva** [comment]
made an additional improvement for utf-8 urls (the ones that where still slow)

see https://github.com/joomla-framework/uri/pull/20/commits/8d48df801a4130fe9c95f4151f7a4ab5efe89695 and please review

with this even those utf-8 urls, when mbstring is available (most cases), goes down from 12ms to 4ms

**Comment by frankmayer** [comment]
strtr in this case is twice as fast as str_replace. Nice one.

**Comment by mbabker** [comment]
What's the status here?

**Comment by andrepereiradasilva** [comment]
work is finished. waiting for reviews
notice in the last commit i removed what i think it's code that as far as i see it was unused. check carefully

**Comment by frankmayer** [comment]
@andrepereiradasilva just a suggestion. Why don't you include the testing instructions (code) from your initial comment into https://github.com/joomla-framework/uri/blob/master/Tests/UriTest.php? Then it would be better (if not fully) tested?

**Comment by andrepereiradasilva** [comment]
this is for 2.0 branch and the tests are in another file https://github.com/joomla-framework/uri/blob/2.0-dev/tests/UriHelperTest.php#L15

**Comment by frankmayer** [comment]
Oh, I see.Thanks for info

**Comment by mbabker** [comment]
If we're going to have benchmarking tests, I think we'd need those in a separate test suite and not something that runs against every commit.  We definitely need benchmarking tests, but they don't have to be as involved in the dev process as unit tests (this can be something we set up in our new CI pipeline, run it once a day/week/month, and make the report available off one of our subdomains).

**Comment by frankmayer** [comment]
@mbabker I meant only the testing part, not the benchmarking part, but I totally agree.

**Comment by mbabker** [comment]
On my MacBook...

Before:
```sh
Michaels-MacBook-Pro:uri mbabker$ php tester.php 
- [6.847 ms] Processing index.php
- [9.263 ms] Processing index.php?ItemId=122
- [10.075 ms] Processing /index.php/username-reminder?view=remind
- [13.252 ms] Processing https://domain.tld/
- [18.129 ms] Processing https://domain.tld/en/about?a=b#anchor
- [23.142 ms] Processing https://domain.tld/path/script.php?foo=%21%2A%27%28%29%3B%3A%40%26%3D%24%2C%2F%3F%23%5B%5D&bar=foo#anchor
- [24.748 ms] Processing https://do身ain.tld/中文/纹身馆简介你好/媒体报道
```

After:
```sh
Michaels-MacBook-Pro:uri mbabker$ php tester.php 
- [6.320 ms] Processing index.php
- [6.272 ms] Processing index.php?ItemId=122
- [6.073 ms] Processing /index.php/username-reminder?view=remind
- [6.156 ms] Processing https://domain.tld/
- [5.954 ms] Processing https://domain.tld/en/about?a=b#anchor
- [8.268 ms] Processing https://domain.tld/path/script.php?foo=%21%2A%27%28%29%3B%3A%40%26%3D%24%2C%2F%3F%23%5B%5D&bar=foo#anchor
- [26.256 ms] Processing https://do身ain.tld/中文/纹身馆简介你好/媒体报道
```

**Comment by mbabker** [comment]
And on an Ubuntu 16.04 test server:

Before:
```sh
- [2.474 ms] Processing index.php
- [3.704 ms] Processing index.php?ItemId=122
- [4.367 ms] Processing /index.php/username-reminder?view=remind
- [4.660 ms] Processing https://domain.tld/
- [7.375 ms] Processing https://domain.tld/en/about?a=b#anchor
- [11.584 ms] Processing https://domain.tld/path/script.php?foo=%21%2A%27%28%29%3B%3A%40%26%3D%24%2C%2F%3F%23%5B%5D&bar=foo#anchor
- [12.306 ms] Processing https://do身ain.tld/中文/纹身馆简介你好/媒体报道
```

After:
```sh
- [1.008 ms] Processing index.php
- [1.087 ms] Processing index.php?ItemId=122
- [1.162 ms] Processing /index.php/username-reminder?view=remind
- [1.317 ms] Processing https://domain.tld/
- [1.787 ms] Processing https://domain.tld/en/about?a=b#anchor
- [2.240 ms] Processing https://domain.tld/path/script.php?foo=%21%2A%27%28%29%3B%3A%40%26%3D%24%2C%2F%3F%23%5B%5D&bar=foo#anchor
- [5.499 ms] Processing https://do身ain.tld/中文/纹身馆简介你好/媒体报道
```

**Pull request merged**
