### PR TITLE
Ensure Compatibility to supported range of PHP Versions

### PR DESCRIPTION
**Pull request by nibra**
Pull Request for Issue #

### CODE REVIEW

**Comment by wilsonge** [comment]
Removing the array typehint from the `buildQuery` isn't required - it still was fully compatible with our php version hitlist and additionally broke the cms (see https://github.com/joomla/joomla-cms/pull/37589 )

**Comment by laoneo** [comment]
@nibra do you revert that change, otherwise we need to patch the CMS?

**Comment by nibra** [comment]
Will do

**Comment by laoneo** [comment]
Here we go #33

**Pull request merged**
